name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run flake8
      run: flake8 app/ tests/ --max-line-length=88 --show-source
    - name: Run isort
      run: isort app/ tests/ --check-only --diff
    - name: Run black
      run: black app/ tests/ --check --diff
    - name: Run mypy
      run: mypy app/ --ignore-missing-imports
    - name: Run tests
      run: pytest tests/ -v
